from __future__ import annotations

ROI_POINTS = []

PROXIMITY_RADIUS_FRAC = 0.18
PROXIMITY_RADIUS_PX: int | None = None

OVERCROWD_TRIGGER_FRAMES = 20

FALL_WIDTH_HEIGHT_RATIO = 1.5
FALL_CONFIRM_SECONDS = 2.0

ALERT_COOLDOWN_SECONDS = 2.0

EVIDENCE_COOLDOWN_SECONDS = 5.0

EVIDENCE_DIR = "static/evidence"

PROXIMITY_MIN_PEOPLE = 4

DISPLAY_ID_MATCH_RADIUS_PX = 110.0
DISPLAY_ID_STALE_SECONDS = 5.0

DISPLAY_MIN_TRACK_AREA_FRAC: float | None = None
